language: ruby
rvm:
  - 2.4.6
  - 2.5.5
  - 2.6.3
gemfile:
  - gemfiles/shrine_2.0.1.gemfile
  - gemfiles/shrine_2.1.1.gemfile
  - gemfiles/shrine_2.2.0.gemfile
  - gemfiles/shrine_2.3.1.gemfile
  - gemfiles/shrine_2.4.1.gemfile
  - gemfiles/shrine_2.5.0.gemfile
  - gemfiles/shrine_2.6.1.gemfile
  - gemfiles/shrine_2.7.0.gemfile
  - gemfiles/shrine_2.8.0.gemfile
  - gemfiles/shrine_2.9.0.gemfile
  - gemfiles/shrine_2.10.0.gemfile
  - gemfiles/shrine_2.11.0.gemfile
  - gemfiles/shrine_2.12.0.gemfile
  - gemfiles/shrine_2.13.0.gemfile
  - gemfiles/shrine_2.14.0.gemfile
  - gemfiles/shrine_2.15.0.gemfile
  - gemfiles/shrine_2.16.0.gemfile
matrix:
  allow_failures:
    - gemfile: gemfiles/shrine_2.4.1.gemfile
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
