name: Run Tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby_version:
          - 2.7.5
          - 3.0.5
          - 3.1.4
          - 3.2.2
        shrine_version:
          - 2.0.1
          - 2.1.1
          - 2.2.0
          - 2.3.1
          - 2.5.0
          - 2.6.1
          - 2.7.0
          - 2.8.0
          - 2.9.0
          - 2.10.1
          - 2.11.0
          - 2.12.0
          - 2.13.0
          - 2.14.0
          - 2.15.0
          - 2.16.0
          - 2.17.1
          - 2.18.1
          - 2.19.3
          - 3.0.0
          - 3.0.1
          - 3.1.0
          - 3.2.0
          - 3.2.1
          - 3.2.2
          - 3.3.0
          - 3.4.0
          - 3.5.0

    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/shrine_${{ matrix.shrine_version }}.gemfile
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true
      - run: bundle exec rake spec

